services:
  web:
    image: webdevops/php-apache:8.2
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
      - DATABASE_URL=mysql://cakephp_user:cakephp_password@db/cakephp_db
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cakephp_db
      MYSQL_USER: cakephp_user
      MYSQL_PASSWORD: cakephp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
